branches:
  only:
  - "/^v[0-9]/"
env:
  global:
  - secure: we+fjtEl+EQU2B6YwhXs0/1Ms9+/jC++t0/5rYixl9CLHZDE9yuisKEkhTDJ1ot0bvbzX8GtEYzYuRZ3113oJdGMa9+AMdXa1Pzl4utymk7YcBqQ0FDBafT2IeTfBQ0obqkeNRhX5hBQOLAb7MAxTBAv0q+JFMsXYN185CGWdknb5Q3BBZKyfstQFeBTRy8o6Jn+okLezjcHn36eCS1TfcHhvuwxlcmIr2GU9xpWQs0hsqNC+ZHZCCBbiTaomWhnhAsFoA5vH2Nbi6QmPQEAmlT4hVKUf/Fhn5d+qwqSi5vcauOOED3eHyv3RzdOxFuQE4fzZE/R+9CUuT01K7Kts/lQz4Mu58e6xw6xczCIuo1yeWDA7kKpkWnGKFBDG3rgPch6FOmuBotwOJuoOlZfLb2qjiQ1DAk6D4lHQNAt1tLtBpX8USGXiqF2xyRZyZwmUoigz/RKp32ZHjgEkMkfUuA2hhvMzQSOTpQvV9csloG9LXs01s1+WSrVec1IbANlGffzqKZRSD9DL4raguf3Swt0tFb9nR/UnJhVwL0wdat+HyYhpAAHohpZifT/po/yny8FlfPmFt14uh9qGO36Eu9tWXMuLt8fvTIbZA0oRgT8TXANR8qOUg34UH78ZXC6h+4QtAFHWdoSiwRJMdsbIjcVGsjEMC4I/O9DJzD7yq4=
  - secure: ldNeONzUqMfRkGaWdD9vEHkUx0pKAuA70Dnt+I/SZLKuvxQeB2NoFr6PBNEjdDSI2l/bsmpRj0Oqlo4d7dNO0fFa/PQ4WF2nY504eHSJzkJJJ7EHyqhMEheqDh96XWOrrpTsv/bjJr1GHCiyXKy6n0IMm81LcfD78bePPAS51/ajYhaUtJBt3xUSkkLtQEGYSGdJSwGqTuGt2MaeQNMfASF1GO/fR4k83L11S/SqYgcfKbmj/5Ow6NDQ5WaIeXRPEEnKYNjLKRmCSmxdOfWlbZ3v3zNjW4swEx9IvqSuSu6uxXOxcOuWqiWg6ibaeYJj5eA0WFYW+rPnWvP2fXPTqEBXeYN73lOPLXNr16JVBoH5pEMUHrzG9j3fGQCI13y4wrYmCkc1yJElxp1hxqc/Cn5LNBMfutclCQIpgKMFfAzM0yP+JkwMty3oROzO4RysucN4DZxXo14LzeQVgmD8++d72og/5faNJx1ql27SLuVb9ycM85xjDcWmF0zJRTwv3dU01mNPPuh8adSG/HzKh4PbaL7l9yOuHgrOVoHo09iHJloMOd8PUUtXdzGUJiLZbHpEzf4S2GAIksgO/MMbmzD3oiwfsUk0LQ97BNYUdMQyVDShSvv4zNFior5mC0Z4vkpYfa9eXZ4nhPdu95qxM2kkzGhJFgm+gS2CLaTOnyI=
matrix:
  include:
  - os: linux
    language: node_js
    node_js: '8'
    after_success:
    - yarn global add meshblu-connector-schema-generator meshblu-connector-uploader-github
    - mkdir -p ./deploy/assets
    - meshblu-connector-schema-generator > ./deploy/assets/schemas.json
    - meshblu-connector-uploader-github --installers-path ./deploy/assets
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-armv7
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-armv7 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x86
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-x86 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x64
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/meshblu-connector-builder:linux-x64 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
  - os: osx
    node_js: '8'
    language: node_js
    after_success:
    - yarn global add meshblu-connector-pkger meshblu-connector-installer-macos meshblu-connector-uploader-github
    - meshblu-connector-pkger && meshblu-connector-installer-macos && meshblu-connector-uploader-github
