language: node_js
node_js:
  - '7'
os:
- linux
- osx
branches:
  only:
  - '/^v[0-9]/'
  - executable-build
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
before_deploy:
- ./build.sh
deploy:
- provider: releases
  api_key:
    secure: "sgsMypPCcSYVXu40U+utZZ0akfriJqVDyQRPE+QAjZV4MwZFAAqmBXiNtuyznbM0WXDugdsE2mc70/swatrE37slmu7QEMVGVyEnkAnI2c7nbpKz6r1AMQjIQ7SiarxrfprGWPgPXpiy78muxoIjqxrwPH2vmlgAY0GdTuxdP233TBLm7zDRJnRs7MJTf41iyu4YV6VjGicMigLKYR+bl6Iz9rAzbzTOYadAza4kaGo2Gj2QJtQHG+EyPuq3dKOWnl3uolmWgohLcU6DJAu8xfnBnIT2bMN/l5dj4tgZSRmZEP/rtfzhqKkRqrnnIR4NcYaOtTaGZEM/3ScpQTGUXgb9YHmBeMOZQaLsVDRD+KQco1nxbTdy98q/11NIfiVTXVYVmSxOZUUuwYfVd7e5B7f0/ERh4m2xetsF8Rfnh5tr+rtLEqarkBeW/KCvRyt3nPDFFRRsOY9rCvXvemzZ3GiyykV/why5L7+/WXMv25cKhPnVl+YyZ09EPSzHhxEDGlhdN0tozhgF+NWTyl42pWliH2hDj4mjHZSvtU39eEmFL1rI4+azc5i9aPEfVfnvkQK7jlHRYo98EoLzWjNkFNPyALJSuBncvCpl6Dd/oMVRfDHr/4nhnM1a7S2yZD6NNhtIoWcUG+h9Y7iu40Uu5RhRG67YkIQUwTC2jr2F8tM="
  file_glob: true
  file:
  - "dist/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "uTNCvXU1tSHoOeLUzMq9rJbWKl03SlwZ0FiI40iEZNkbVn9HDt/nLWH47KCdqVQJhmtRcWhUlqURtC18JGHNO84I+D18lYeklncwrf2nSbTjFTANrX9WHWTRhxZNAEuLfuPvukHJHUZUq1KyG8kvTVGTnL1Fq/spoJlU8xJdb+4i8oCAQenMo30N5SvGoD8CCK+RgTCJlpc23JTpvLmlz0XfMq2rknji0HU2RDU7TMzCF0Tpb/i4cMauIQOuLv6kqFxcz1ESxMz+nT54elFM0yy2Vi4w/0Ay2vonC+WPYCrLDxRBRsJZ4gHzYixH9raVDEtTb0dszmCnxx42KnZme1+rUIze1xiwpFTYwlh6Oswtg+ILpbTwmbK5rhqsSF0C16dnnyGomJoOi55DuL/wrx4Exsl9hyA+vaXxitXWOlcAYt0Mqct8E1SZrui6fLKKNzVrLEAfOsgIWKMqjxhtrtIQsJrOi4ach8mPqCCQXLsZ2NzSrC604hCWphDO4Asn+rdIsbImExz94TaCVqm9sZf9QtRLKy8gARC+u8S7v3pWn8SlwBgYGToGK710E/CBJleOQHT0XQwAedZ17aZ5cNKvHnqXWgVL3gof60Ww9G33zmGj5NUkV8lWYfmaM0Ct7j7jjrYUjCZFDVQs0GFRzxBeV8OPrEwk5Chebpkf5Kc="
  on:
    tags: true
